Add tips to help with input
NBISweden/assembly-project-template pull request #24
Opened 2024-11-13 09:54 UTC by mahesh-panchal

Add tips to assembly parameters to help with generating input.

2024-11-13 10:14 UTC, gbdias requested changes

2024-11-13 10:14 UTC, gbdias commented on analyses/01_ebp-assembly-workflow/assembly_parameters.yml
> +#   <( find ../../data/raw-data/Illumiuna-HiC/ -name '*_R1.fastq.gz' -exec echo "  - read1: {}" \; | sort ) \
typo in "/Illumina-HiC/"

2024-11-13 10:21 UTC, mahesh-panchal commented on analyses/01_ebp-assembly-workflow/assembly_parameters.yml
> +#   <( find ../../data/raw-data/Illumiuna-HiC/ -name '*_R1.fastq.gz' -exec echo "  - read1: {}" \; | sort ) \
Thanks

2024-11-19 08:41 UTC, gbdias approved these changes
All good now 👍

2024-11-19 08:43 UTC, merged